#!/usr/bin/env bash
# Servers are the places where software generating and serving HTML pages
# Installing nginx on web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
listen 8080;
