#!/usr/bin/env bash
# 3-redirection

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a new configuration file for the redirection
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Enable the configuration by creating a symlink to sites-enabled
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx
