#!/usr/bin/env bash
# Servers are the peice of software generating and serving HTTP pages
# Installing nginx on web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

# Create a backup of the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sed -i '/listen 80 defult_server/a rewrite ^/redirect_me https://www.youtupe.com/@walaacoder permenet;' /etc/nginx/sites-available/default

sudo nginx -t

service nginx restart
