#!/usr/bin/env bash
# Installing Nginx with the following configurations:
#+	Listens on port 80
#+	Returns a page containing "Holberton School" when queried
#+	at the root with curl GET request.
# Configres /redirect_me as a "301 Moved Permenently".
# Includes a custom 404 page containing "Ceci n'est pas une page"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 defult_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    # Location for the root of the site
    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    # Custom 404 error page
    error_page 404 /404.html;
    location = /404.html {
        root /etc/nginx/html;
	internal;
    }
}" > /etc/nginx/sites-available/defult

service nginx restart
