#!/usr/bin/env bash
# Installing load balancer

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    #shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "       Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "       ${1} is already installed.\n"
    fi
}

install haproxy # Install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend clickviral-tech-frontend
    bind ':80'
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 522130-web-01 52.87.235.32:80 check
    server 522130-web-02 54.166.172.96:80 check
"

# Write the new configuration to haproxy.cfg
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Check if haproxy is running and start/restart it accordingly
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

# Output message with server names as required
echo '["web-01", "web-02"]'
