#!/usr/bin/env bash
# i love you
clean_up_='rm /var/run/myscript.pid; exit $?'

echo $$ > "/var/run/myscript.pid"

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 1
done
