#!/usr/bin/env bash
# i love you
echo $$ > /var/run/myscript.pid

trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 1
done
