#!/usr/bin/env bash
# This script tells a story based on the content of /etc/passwd
# Set IFS to ":" to parse fields in /etc/passwd
IFS=":"

# Read /etc/passwd line by line
while read -r username password userid groupid info homedir shell; do
  # Print the formatted output
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
