#!/usr/bin/env bash

# Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.1
# facebook.com resolves to 157.240.11.35
# The checker is running on Docker

cp /etc/hosts ~/hosts.new
echo "127.0.0.1 localhost" > ~/hosts.new
echo "157.240.11.35 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
